"""lms update

Revision ID: 9a32e962e8a7
Revises: ab6a13f6c62a
Create Date: 2026-09-29 12:13:15.217953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a32e962e8a7'
down_revision: Union[str, Sequence[str], None] = 'ab6a13f6c62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'user_id', name='uq_attendance_schedule_user')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.add_column('homework', sa.Column('tasks_count', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('link', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('status', sa.String(), server_default='submitted', nullable=False))
    op.add_column('submissions', sa.Column('teacher_comment', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('task_results', sa.JSON(), nullable=True))
    op.add_column('submissions', sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint('uq_submission_homework_user', 'submissions', ['homework_id', 'user_id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint('uq_submission_homework_user', 'submissions', type_='unique')
    op.drop_column('submissions', 'reviewed_at')
    op.drop_column('submissions', 'task_results')
    op.drop_column('submissions', 'teacher_comment')
    op.drop_column('submissions', 'status')
    op.drop_column('submissions', 'comment')
    op.drop_column('submissions', 'link')
    op.drop_column('homework', 'tasks_count')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
