"""add link to homework

Revision ID: ab6a13f6c62a
Revises: 3f2584d12dda
Create Date: 2026-09-29 04:46:49.451120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6a13f6c62a'
down_revision: Union[str, Sequence[str], None] = '3f2584d12dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'link')
    # ### end Alembic commands ###
