"""add lessons

Revision ID: bc11af18c3c3
Revises: 09e5f4a73e47
Create Date: 2026-10-01 08:50:32.612743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc11af18c3c3'
down_revision: Union[str, Sequence[str], None] = '09e5f4a73e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='lesson', nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('webinar_link', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('notes_url', sa.String(), nullable=True),
    sa.Column('homework_text', sa.Text(), nullable=True),
    sa.Column('homework_link', sa.String(), nullable=True),
    sa.Column('tasks_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_course_id'), 'lessons', ['course_id'], unique=False)
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('lesson_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_lesson_attendance_user')
    )
    op.create_index(op.f('ix_lesson_attendance_id'), 'lesson_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_attendance_lesson_id'), 'lesson_attendance', ['lesson_id'], unique=False)
    op.create_table('lesson_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='submitted', nullable=False),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('task_results', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'user_id', name='uq_lesson_submission_user')
    )
    op.create_index(op.f('ix_lesson_submissions_id'), 'lesson_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_submissions_lesson_id'), 'lesson_submissions', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_submissions_lesson_id'), table_name='lesson_submissions')
    op.drop_index(op.f('ix_lesson_submissions_id'), table_name='lesson_submissions')
    op.drop_table('lesson_submissions')
    op.drop_index(op.f('ix_lesson_attendance_lesson_id'), table_name='lesson_attendance')
    op.drop_index(op.f('ix_lesson_attendance_id'), table_name='lesson_attendance')
    op.drop_table('lesson_attendance')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_course_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
